# 简化的Searx测试部署 - 单节点测试
version: '3.8'

services:
  # 单个Searx节点用于测试
  searx-test:
    image: searxng/searxng:latest
    container_name: searx-test
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_SECRET=test-secret-key-for-development
      - SEARXNG_HOSTNAME=searx-test
      - SEARXNG_PORT=8080
      - SEARXNG_BIND_ADDRESS=0.0.0.0
    volumes:
      - ./searx-test-config:/etc/searxng:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "searx.node=test"
      - "searx.weight=10"

networks:
  default:
    driver: bridge
